### ISSUE TITLE
Animations From All Gamebuilds 

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [Mathu-lmn/mth-animations#1]
Hey, awesome work! Sorry, not a  issue but you can use [this](https://github.com/DurtyFree/gta-v-data-dumps/blob/master/animDictsCompact.json) GitHub page to find all animation directories and names up to the latest gamebuild, and then in the code, I believe if you add `DoesAnimDictExist` what'll happen is, if a server isn't on the latest gamebuild, animations from a higher gamebuild, won't appear in the menu; something like this:

```lua
function LoadAnim(dict)
    if not DoesAnimDictExist(dict) then
        return false
    end

    while not HasAnimDictLoaded(dict) do
        RequestAnimDict(dict)
        Wait(10)
    end

    return true
end
```

Also make sure to credit @DurtyFree for the GitHub page thing 🙂

**Comment by Mathu-lmn** [comment]
Hey, thanks for the feedback, I'll update the script asap :)

**Comment by Mathu-lmn** [comment]
Updated !

**Comment by TayMcKenzieNZ** [comment]
😎
